[project]
name = "myllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.3.0",
    "clearml>=1.17.1",
    "datasets>=3.3.0",
    "deepspeed>=0.16.3",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "tabulate>=0.9.0",
    "toml>=0.10.2",
    "torch>=2.6.0",
    "torchsummary>=1.5.1",
    "tqdm>=4.67.1",
    "transformers>=4.48.3",
    "trl>=0.16.0",
    "wandb>=0.19.6",
]
