compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: configs/deepspeed/stage_3.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
# deepspeed_hostfile: hostfile
downcast_bf16: 'no'
enable_cpu_affinity: false
# main_process_ip: 172.28.67.10
# main_process_port: 29500
main_training_function: main
num_processes: 2
# num_machines: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
