from __future__ import annotations

"""Entrypoint enabling ``python -m myllm`` as well as ``accelerate launch myllm ...``.
Accelerate multi-GPU launcher expects the target to be importable as a module;
console scripts generated by setuptools are not importable, therefore we
forward to CLI ``main`` here.
"""

from myllm.cli import main

if __name__ == "__main__":  # pragma: no cover
    main() 