apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests.yaml
patchesStrategicMerge:
- |-
  apiVersion: admissionregistration.k8s.io/v1
  kind: ValidatingWebhookConfiguration
  metadata:
    name: validating-webhook-configuration
  webhooks:
  - name: validator.clustertrainingruntime.trainer.kubeflow.org
    failurePolicy: Ignore
  - name: validator.trainingruntime.trainer.kubeflow.org
    failurePolicy: Ignore
  - name: validator.trainjob.trainer.kubeflow.org
    failurePolicy: Ignore
configurations:
  - kustomizeconfig.yaml
