name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Create and configure virtual environment
      run: |
        python -m venv .venv
        echo ".venv/bin" >> $GITHUB_PATH

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies with pip
      run: |
        pip install -e .

    - name: Install dependencies with uv
      run: |
        uv pip install -e .

  docker-build:
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job
    timeout-minutes: 45  # Increase timeout to 45 minutes
    # Only run on main branch or when commit message contains [docker]
    if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[docker]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Do not push the image for now
          tags: myllm:latest
          # Use GitHub Actions cache for better performance
          cache-from: type=gha
          cache-to: type=gha,mode=max